--DROP TABLE books CASCADE CONSTRAINTS;
--DROP TABLE members CASCADE CONSTRAINTS;
--DROP TABLE borrow_books CASCADE CONSTRAINTS;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER books IDENTIFIED BY 1234;
GRANT resource, dba, CONNECT TO books;
GRANT CREATE ANY TABLE TO books;