CREATE TABLE books (
    id             NUMBER 			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR2(50) 	NOT NULL,
    author         VARCHAR2(50) 	NOT NULL,
    publisher      VARCHAR2(50) 	NOT NULL,
    quantity       NUMBER 			NOT NULL
);

CREATE TABLE members (
    id             NUMBER 			GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR2(50) 	NOT NULL,
    phone          VARCHAR2(50) 	NOT NULL
);

CREATE TABLE borrow_books (
    member_id      NUMBER 			REFERENCES members(id),
    book_id        NUMBER 			REFERENCES books(id),
    PRIMARY KEY (member_id, book_id)
);
