
server:
  port: 8080
  servlet:
    encoding:
      force: true

spring:

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  sql:
    init:
      mode: always

  application:
    name: firstproject

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
